# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate aemcmc-dev
#
name: aemcmc-dev
channels:
  - conda-forge
dependencies:
  - python
  - compilers
  - numpy>=1.18.1
  - scipy>=1.4.0
  - aesara>=2.8.0
  - aeppl>=0.0.35
  - aehmc>=0.0.9
  - polyagamma>=1.3.2
  - cons
  - logical-unification
  - etuples
  - miniKanren
  # Intel BLAS
  - mkl
  - mkl-service
  - libblas=*=*mkl
  # For testing
  - pytest
  - coverage>=5.1
  - coveralls
  - pytest-cov
  - pytest-xdist
  # For building docs
  - sphinx>=1.3
  - sphinx_rtd_theme
  - pygments
  - pydot
  - ipython
  # developer tools
  - pre-commit
  - packaging
  - typing_extensions
